### ISSUE TITLE
Tagged structural links

### ISSUE THREAD

**Issue by meinnameistannalena** [TobiasWeis/pyOPM#1]
Hi,
diese Tagged Structural Links wäre auch noch hilfreich. Zumindest die 2 oberen (tagged und null).

![img_20160429_141709](https://cloud.githubusercontent.com/assets/18569791/14915712/5593e13e-0e15-11e6-9504-218c598f3b61.jpg)

Und der Vollständigkeit halber müssten auch noch weitere Tags wie z.B. 'm' für many oder '5', an die Link-Enden.

**Comment by TobiasWeis** [comment]
![updated](https://cloud.githubusercontent.com/assets/6633810/14917133/d232acd6-0e1d-11e6-8a41-0671dae47ffd.png)
Noch nicht schön, aber selbstgemacht. Goal: Erstmal Grund-Funktionalität, dann styling..
